
import operator

text = "CCGTTCGGCACTATCGGCAGCTATCGGCAGCTATCGGCAGCCGTTCGGCACTATCGGCAGCTATCGGCAGCCGTTCGGCACCCTTTGGTGTCGCACTTACTATCGGCAGCCCTTTGGTGCTATCGGCAGCTATCGGCAGTCGCACTTACGTGGAACGTCCCTTTGGTGCGTGGAACGTCCCTTTGGTGCCGTTCGGCACTATCGGCAGCTATCGGCAGCCCTTTGGTGCCCTTTGGTGTCGCACTTATCGCACTTATCGCACTTATCGCACTTACCCTTTGGTGCTATCGGCAGCCCTTTGGTGCCCTTTGGTGTCGCACTTACGTGGAACGTCTATCGGCAGTCGCACTTATCGCACTTACGTGGAACGTTCGCACTTACCGTTCGGCACCCTTTGGTGCTATCGGCAGCGTGGAACGTTCGCACTTACTATCGGCAGCGTGGAACGTCCCTTTGGTGCCGTTCGGCACCGTTCGGCACCGTTCGGCACGTGGAACGTCTATCGGCAGCGTGGAACGTCCCTTTGGTGCGTGGAACGTTCGCACTTACGTGGAACGTCCGTTCGGCACCGTTCGGCACTATCGGCAGCCGTTCGGCACGTGGAACGTCCGTTCGGCACCCTTTGGTGCCGTTCGGCACTATCGGCAGCCGTTCGGCACCCTTTGGTGCCGTTCGGCACGTGGAACGTCCCTTTGGTGCCCTTTGGTGTCGCACTTACGTGGAACGTCCCTTTGGTGCGTGGAACGTCCGTTCGGCACGTGGAACGTCCCTTTGGTGCCCTTTGGTGCCGTTCGGCATCGCACTTACCCTTTGGTGTCGCACTTATCGCACTTACTATCGGCAGCTATCGGCAGCCGTTCGGCACGTGGAACGTCTATCGGCAGCCGTTCGGCACCGTTCGGCACGTGGAACGTCTATCGGCAGCTATCGGCAG"
k = 12

kmers = dict()

for i in range(len(text) - 12):
    kmer = text[i:i + 12]
    if  kmer in kmers:
        kmers[kmer] = kmers[kmer] + 1
    else:
        kmers[kmer] = 1

sorted_kmers = sorted(kmers.items(), key=operator.itemgetter(1), reverse=True)

max_count = sorted_kmers[0][1]
result = []

for kmer in sorted_kmers:
    if kmer[1] < max_count:
        break
    else:
        result.append(kmer[0])

print(result)
print(max_count)
